services:
  - type: web
    name: delta-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
